# Generated by Django 2.2 on 2020-12-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Candle'), ('SG', 'Shower Gel'), ('L', 'Lotion'), ('HS', 'Hand Soap')], default='S', max_length=2),
        ),
    ]
